# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muno < Formula
  desc "Multi-repository UNified Orchestration for Claude Code agents"
  homepage "https://github.com/taokim/muno"
  version "0.9.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/taokim/muno/releases/download/v0.9.2/muno_Darwin_x86_64.tar.gz"
      sha256 "b651f3cdbc231de479186e2744c2914d0fd02786c77f663f49f820685fce1ac8"

      def install
        bin.install "muno"
      end
    end
    on_arm do
      url "https://github.com/taokim/muno/releases/download/v0.9.2/muno_Darwin_arm64.tar.gz"
      sha256 "7326982ca584caee8744cc1f2489513bd82d98de42ca60340a6310958d82a515"

      def install
        bin.install "muno"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/muno/releases/download/v0.9.2/muno_Linux_x86_64.tar.gz"
        sha256 "57879be6049fe61906e3c5d316b1f9721968e269daeea18d8cf3f0f6c491a9f4"

        def install
          bin.install "muno"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/muno/releases/download/v0.9.2/muno_Linux_arm64.tar.gz"
        sha256 "e6f6d3f2696b1e135a0afa821c78a6556bd341bf35675729897cc539cfb9676d"

        def install
          bin.install "muno"
        end
      end
    end
  end

  test do
    system "#{bin}/muno", "--version"
  end
end
