# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muno < Formula
  desc "Multi-repository UNified Orchestration for Claude Code agents"
  homepage "https://github.com/taokim/muno"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/taokim/muno/releases/download/v1.0.3/muno_Darwin_x86_64.tar.gz"
      sha256 "8a428576796775adf66179428996f6d740db2e71ff6c5aa7ca93a9e59523c1a8"

      def install
        bin.install "muno"
      end
    end
    on_arm do
      url "https://github.com/taokim/muno/releases/download/v1.0.3/muno_Darwin_arm64.tar.gz"
      sha256 "e32c5d50caecfd3f80cf21d5f45f5d539bd4b8c7fe5718b25259c55ee2e39b18"

      def install
        bin.install "muno"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/muno/releases/download/v1.0.3/muno_Linux_x86_64.tar.gz"
        sha256 "efa7a2ddfadf4fc93d00f7a56357825d342056694fd0270b591341070b9da318"

        def install
          bin.install "muno"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/muno/releases/download/v1.0.3/muno_Linux_arm64.tar.gz"
        sha256 "cf44995fb8b528d0ec1987196007ee8d4b59ee1f90efb39dda31236ef6895196"

        def install
          bin.install "muno"
        end
      end
    end
  end

  test do
    system "#{bin}/muno", "--version"
  end
end
