# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoClaude < Formula
  desc "Multi-repository orchestration for Claude Code agents"
  homepage "https://github.com/taokim/repo-claude"
  version "0.4.0"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/taokim/repo-claude/releases/download/v0.4.0/repo-claude_Darwin_x86_64.tar.gz"
      sha256 "6e7c68a89c0b7d16c37f5be7fc0ef6301fd8c2ffbb21c6409920c349713e9616"

      def install
        bin.install "rc"
      end
    end
    on_arm do
      url "https://github.com/taokim/repo-claude/releases/download/v0.4.0/repo-claude_Darwin_arm64.tar.gz"
      sha256 "bb9144c4a1d63bac913e770abba0f4efeb7379266726838afaa50e0403e2e649"

      def install
        bin.install "rc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.4.0/repo-claude_Linux_x86_64.tar.gz"
        sha256 "4ca1f4026ee55da7765edbd0ccd2dc0a0cf5d8bd67a60bdbc715a3e0f1f48143"

        def install
          bin.install "rc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.4.0/repo-claude_Linux_arm64.tar.gz"
        sha256 "75c5f152539c57fdc70edff3b5d70a6a2db9f108bb7307679f5789a9e7e17fa5"

        def install
          bin.install "rc"
        end
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
  end
end
