# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoClaude < Formula
  desc "Multi-agent orchestration using Repo tool and Claude Code"
  homepage "https://github.com/taokim/repo-claude"
  version "0.1.4"
  license "MIT"

  depends_on "git"
  depends_on "repo"

  on_macos do
    on_intel do
      url "https://github.com/taokim/repo-claude/releases/download/v0.1.4/repo-claude_Darwin_x86_64.tar.gz"
      sha256 "e8b3f292fc0030f97df78a45a69482c08ebc2812780b191a6cb0133f70eddbbe"

      def install
        bin.install "rc"
      end
    end
    on_arm do
      url "https://github.com/taokim/repo-claude/releases/download/v0.1.4/repo-claude_Darwin_arm64.tar.gz"
      sha256 "0ca45b22a5cb14b03ebf56604f0b0b5d45f701bef39f7d33489e3fa74abeca5e"

      def install
        bin.install "rc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.1.4/repo-claude_Linux_x86_64.tar.gz"
        sha256 "ffc17afc34345de48b48ed22da0bc655d3b7c735f72f2dff8d16be961c96a40b"

        def install
          bin.install "rc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.1.4/repo-claude_Linux_arm64.tar.gz"
        sha256 "45d8fc2cc30afdaf7b1bc6622aad67850474b5af7f2f53f5fedee11f97da8244"

        def install
          bin.install "rc"
        end
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
  end
end
