# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoClaude < Formula
  desc "Multi-agent orchestration using Repo tool and Claude Code"
  homepage "https://github.com/taokim/repo-claude"
  version "0.1.3"
  license "MIT"

  depends_on "git"
  depends_on "repo"

  on_macos do
    on_intel do
      url "https://github.com/taokim/repo-claude/releases/download/v0.1.3/repo-claude_Darwin_x86_64.tar.gz"
      sha256 "b2b505d9a4a9d05095e4b0739d8d08992118542db62d15342c4339e269a49ef9"

      def install
        bin.install "rc"
      end
    end
    on_arm do
      url "https://github.com/taokim/repo-claude/releases/download/v0.1.3/repo-claude_Darwin_arm64.tar.gz"
      sha256 "2ad7933bb66415c8786b43e67e470f3f1cfa7981c132faaa3ddff2205a7c7d82"

      def install
        bin.install "rc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.1.3/repo-claude_Linux_x86_64.tar.gz"
        sha256 "69f3b11e586b4068d121b7d12987dc54b1cbecbf08c01cf5ced54a1a2919f0f7"

        def install
          bin.install "rc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/taokim/repo-claude/releases/download/v0.1.3/repo-claude_Linux_arm64.tar.gz"
        sha256 "58ee56b5e462a487c351cdc94f77263c0807dfaa168e217ae414a4970323a4cb"

        def install
          bin.install "rc"
        end
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
  end
end
